# Generated by Django 2.2 on 2020-04-21 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('option_1', models.CharField(max_length=10000)),
                ('option_2', models.CharField(blank=True, max_length=10000, null=True)),
                ('option_3', models.CharField(blank=True, max_length=10000, null=True)),
                ('option_4', models.CharField(blank=True, max_length=10000, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=10000, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
            ],
        ),
    ]
