# Generated by Django 3.0.5 on 2020-04-26 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['category__name'], 'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='category',
            name='dedicated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.Category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques',
            field=models.CharField(max_length=100000),
        ),
    ]
